name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jvmazagao
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'

      # Commit the new files
      - name: Commit snake assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git diff --cached --quiet || git commit -m "chore: update snake contribution graph"

      # Create or update a PR against main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore: update snake graph
          title: chore: update snake contribution graph
          body: |
            This PR was generated by GitHub Actions to update the contribution snake.
          base: main
          branch: update-snake-${{ github.run_id }}
